project:
  type: book
  output-dir: _book

book:
  title: "Изучение древних микроорганизмов группы HACEK с точки зрения эволюционной биологии"
  author: "Флоренская Лидия"
  chapters:
    - index.qmd
    - chapters/download_assemblies.qmd
    - chapters/create_consensus_from_BAM.qmd
    - chapters/annotate_assemblies.qmd
    - chapters/make_core_alignment.qmd
    # ...
  repo-url: https://github.com/florenskaial118/MASTER_DIPLOMA.git
  repo-actions: [edit, source, issue]

bibliography: references.bib  


format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
