---
title: Скачиваем метаданные о сборках
engine: knitr
---


*Cardiobacterium hominis*, *Eikenella corrodens*, *Aggregatibacter actinomycetemcomitans* 


```{bash}
#| eval: false
chmod +x ../scripts/download_assemblies_metadata.sh

../scripts/download_assemblies_metadata.sh "Cardiobacterium hominis" ../data/C_H/assembly_metadata/Cardiobacterium_hominis.tsv
../scripts/download_assemblies_metadata.sh "Eikenella corrodens" ../data/C_H/assembly_metadata/Eikenella_corrodens.tsv
../scripts/download_assemblies_metadata.sh "Aggregatibacter actinomycetemcomitans" ../data/C_H/assembly_metadata/Aggregatibacter_actinomycetemcomitans.tsv
```

```{python}
#| eval: false
import pandas as pd

Cardiobacterium_hominis = pd.read_csv('../data/C_H/assembly_metadata/Cardiobacterium_hominis.tsv', sep = '\t')
Eikenella_corrodens = pd.read_csv('../data/C_H/assembly_metadata/Eikenella_corrodens.tsv', sep = '\t')
Aggregatibacter_actinomycetemcomitans = pd.read_csv('../data/C_H/assembly_metadata/Aggregatibacter_actinomycetemcomitans.tsv', sep = '\t')

with pd.ExcelWriter('../data/C_H/assembly_metadata/combined_info.xlsx') as writer:
    Cardiobacterium_hominis.to_excel(writer, sheet_name='Cardiobacterium_hominis', index=False)
    Eikenella_corrodens.to_excel(writer, sheet_name='Eikenella_corrodens', index=False)
    Aggregatibacter_actinomycetemcomitans.to_excel(writer, sheet_name='Aggregatibacter', index=False) #в названии листа нельзя использовать слишком длинные названия
```

Итоговый xls лежит в [таблице](https://docs.google.com/spreadsheets/d/1ncw5GF4YLnUmx1mQxcyNWPArU9sB6RSFIRYcyxtNu1M/edit?gid=2041904701#gid=2041904701)

Для части сборок уже есть готовая аннотация .gff от Саши, для части - нет. Важно, что нам нужно делать аннотациб вручную, потому что аннотации с сайта NCBI по формату не подходят для дальнейшнего анализа в roary.

# Скачиваем сборки по метаданным

Начнем с *Cardiobacterium Hominis*

На летней практике я работала с этим видом, поэтому для опубликованных на тот момент современных сборок есть анотация. Сравним текущий список сборок с тем, для которого есть аннотаци с лета (убеждаемся, что все уже проаннотированные сборки есть в нашем списке)

```{python}
import pandas as pd
from os import listdir

Cardiobacterium_hominis = pd.read_csv('../data/C_H/assembly_metadata/Cardiobacterium_hominis.tsv', sep = '\t')

all_assembly = [f'{f.split('.1')[0]}.1' for f in Cardiobacterium_hominis['AssemblyAccession']]
annotated_assembly = [f'{f.split('.1')[0]}.1' for f in listdir('../data/C_H/avaliable_gff_C_H')]

intersection = list(set(all_assembly) & set(annotated_assembly))
diff_all = list(set(all_assembly) - set(annotated_assembly))
diff_av = list(set(annotated_assembly) - set(all_assembly))

print(f'Текущее количество сборок в NCBI: {len(all_assembly)}')
print(f'Проаннотированных с лета: {len(annotated_assembly)}')
print(f'Совпадает: {len(intersection)}')
print(f'Тех из летних, что нет в текущем наборе: {len(diff_av)}')
print(f'Тех из текущих, что нет в летних: {len(diff_all)}')

with open('../data/C_H/new_assemblies_C_H/list.txt', 'w') as f:
    for gff in diff_all:
        _ = f.write(f"{gff}\n")

with open('../data/C_H/assemblies_C_H/list.txt', 'w') as f:
    for gff in all_assembly:
        _ = f.write(f"{gff}\n")
```


Новые скачиваем в отдельную папку дл аннотации, а все сборки вместе - в другую папку

```{bash}
#| eval: false
source ../scripts/download_assembly.sh

while read AssemblyAccession; do
    download_assembly "$AssemblyAccession" "../data/C_H/new_assemblies_C_H/${AssemblyAccession}.fa" < /dev/null
done < '../data/C_H/new_assemblies_C_H/list.txt'
```

```{bash}
#| eval: false
while read AssemblyAccession; do
    download_assembly "$AssemblyAccession" "../data/C_H/assemblies_C_H/${AssemblyAccession}.fa" < /dev/null
done < '../data/C_H/assemblies_C_H/list.txt'
```

